# Generated by Django 4.2.7 on 2023-11-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nas', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('reprodutivo', models.CharField(choices=[('FEMEA', 'Femea'), ('MACHO', 'Macho')], max_length=100)),
                ('vacinas', models.CharField(max_length=100)),
                ('medicamentos', models.CharField(max_length=100)),
                ('pai', models.CharField(max_length=100)),
                ('mae', models.CharField(max_length=100)),
            ],
        ),
    ]
